"""empty message

Revision ID: 618d8d0b84a5
Revises: 
Create Date: 2018-05-03 14:02:41.907914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618d8d0b84a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appdb01_description'), 'appdb01', ['description'], unique=True)
    op.create_index(op.f('ix_appdb01_user_image_url'), 'appdb01', ['user_image_url'], unique=True)
    op.create_index(op.f('ix_appdb01_username'), 'appdb01', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appdb01_username'), table_name='appdb01')
    op.drop_index(op.f('ix_appdb01_user_image_url'), table_name='appdb01')
    op.drop_index(op.f('ix_appdb01_description'), table_name='appdb01')
    # ### end Alembic commands ###
